//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerApps.TestEngine.Modules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NamespaceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamespaceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerApps.TestEngine.Modules.NamespaceResource", typeof(NamespaceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;PrivateImplementationDetails&gt;::ComputeStringHash(System.String).
        /// </summary>
        internal static string _PrivateImplementationDetails___ComputeStringHash_System_String_ {
            get {
                return ResourceManager.GetString("<PrivateImplementationDetails>::ComputeStringHash(System.String)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Bcl.AsyncInterfaces.
        /// </summary>
        internal static string Microsoft_Bcl_AsyncInterfaces {
            get {
                return ResourceManager.GetString("Microsoft.Bcl.AsyncInterfaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.CodeAnalysis.
        /// </summary>
        internal static string Microsoft_CodeAnalysis {
            get {
                return ResourceManager.GetString("Microsoft.CodeAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.CSharp.
        /// </summary>
        internal static string Microsoft_CSharp {
            get {
                return ResourceManager.GetString("Microsoft.CSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Extensions.Logging.
        /// </summary>
        internal static string Microsoft_Extensions_Logging {
            get {
                return ResourceManager.GetString("Microsoft.Extensions.Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Playwright.
        /// </summary>
        internal static string Microsoft_Playwright {
            get {
                return ResourceManager.GetString("Microsoft.Playwright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.PowerApps.TestEngine..
        /// </summary>
        internal static string Microsoft_PowerApps_TestEngine_ {
            get {
                return ResourceManager.GetString("Microsoft.PowerApps.TestEngine.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.PowerFx.
        /// </summary>
        internal static string Microsoft_PowerFx {
            get {
                return ResourceManager.GetString("Microsoft.PowerFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to netstandard.
        /// </summary>
        internal static string netstandard {
            get {
                return ResourceManager.GetString("netstandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newtonsoft.Json.
        /// </summary>
        internal static string Newtonsoft_Json {
            get {
                return ResourceManager.GetString("Newtonsoft.Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenCvSharp.
        /// </summary>
        internal static string OpenCvSharp {
            get {
                return ResourceManager.GetString("OpenCvSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission#0.
        /// </summary>
        internal static string Submission_0 {
            get {
                return ResourceManager.GetString("Submission#0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Action.
        /// </summary>
        internal static string System_Action {
            get {
                return ResourceManager.GetString("System.Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ArgumentException.
        /// </summary>
        internal static string System_ArgumentException {
            get {
                return ResourceManager.GetString("System.ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Array.
        /// </summary>
        internal static string System_Array {
            get {
                return ResourceManager.GetString("System.Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Attribute.
        /// </summary>
        internal static string System_Attribute {
            get {
                return ResourceManager.GetString("System.Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Byte.
        /// </summary>
        internal static string System_Byte {
            get {
                return ResourceManager.GetString("System.Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.
        /// </summary>
        internal static string System_Collections {
            get {
                return ResourceManager.GetString("System.Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ComponentModel.Composition.
        /// </summary>
        internal static string System_ComponentModel_Composition {
            get {
                return ResourceManager.GetString("System.ComponentModel.Composition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Console.
        /// </summary>
        internal static string System_Console {
            get {
                return ResourceManager.GetString("System.Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Convert.
        /// </summary>
        internal static string System_Convert {
            get {
                return ResourceManager.GetString("System.Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.DateTime.
        /// </summary>
        internal static string System_DateTime {
            get {
                return ResourceManager.GetString("System.DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Decimal.
        /// </summary>
        internal static string System_Decimal {
            get {
                return ResourceManager.GetString("System.Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Dynamic.
        /// </summary>
        internal static string System_Dynamic {
            get {
                return ResourceManager.GetString("System.Dynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Environment::get_NewLine().
        /// </summary>
        internal static string System_Environment__get_NewLine__ {
            get {
                return ResourceManager.GetString("System.Environment::get_NewLine()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Exception.
        /// </summary>
        internal static string System_Exception {
            get {
                return ResourceManager.GetString("System.Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Func.
        /// </summary>
        internal static string System_Func {
            get {
                return ResourceManager.GetString("System.Func", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.GC::Collect().
        /// </summary>
        internal static string System_GC__Collect__ {
            get {
                return ResourceManager.GetString("System.GC::Collect()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IAsyncDisposable.
        /// </summary>
        internal static string System_IAsyncDisposable {
            get {
                return ResourceManager.GetString("System.IAsyncDisposable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IDisposable.
        /// </summary>
        internal static string System_IDisposable {
            get {
                return ResourceManager.GetString("System.IDisposable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Int32.
        /// </summary>
        internal static string System_Int32 {
            get {
                return ResourceManager.GetString("System.Int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.InvalidOperationException.
        /// </summary>
        internal static string System_InvalidOperationException {
            get {
                return ResourceManager.GetString("System.InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.File::Exists.
        /// </summary>
        internal static string System_IO_File__Exists {
            get {
                return ResourceManager.GetString("System.IO.File::Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.File::WriteAllBytes.
        /// </summary>
        internal static string System_IO_File__WriteAllBytes {
            get {
                return ResourceManager.GetString("System.IO.File::WriteAllBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.File::WriteAllText.
        /// </summary>
        internal static string System_IO_File__WriteAllText {
            get {
                return ResourceManager.GetString("System.IO.File::WriteAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.FileInfo.
        /// </summary>
        internal static string System_IO_FileInfo {
            get {
                return ResourceManager.GetString("System.IO.FileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.FileSystemInfo.
        /// </summary>
        internal static string System_IO_FileSystemInfo {
            get {
                return ResourceManager.GetString("System.IO.FileSystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.InvalidDataException.
        /// </summary>
        internal static string System_IO_InvalidDataException {
            get {
                return ResourceManager.GetString("System.IO.InvalidDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.MemoryStream.
        /// </summary>
        internal static string System_IO_MemoryStream {
            get {
                return ResourceManager.GetString("System.IO.MemoryStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.Path::Combine.
        /// </summary>
        internal static string System_IO_Path__Combine {
            get {
                return ResourceManager.GetString("System.IO.Path::Combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.Path::GetDirectoryName.
        /// </summary>
        internal static string System_IO_Path__GetDirectoryName {
            get {
                return ResourceManager.GetString("System.IO.Path::GetDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.Path::GetExtension.
        /// </summary>
        internal static string System_IO_Path__GetExtension {
            get {
                return ResourceManager.GetString("System.IO.Path::GetExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.Path::GetFileNameWithoutExtension.
        /// </summary>
        internal static string System_IO_Path__GetFileNameWithoutExtension {
            get {
                return ResourceManager.GetString("System.IO.Path::GetFileNameWithoutExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.Path::IsPathRooted.
        /// </summary>
        internal static string System_IO_Path__IsPathRooted {
            get {
                return ResourceManager.GetString("System.IO.Path::IsPathRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.Stream.
        /// </summary>
        internal static string System_IO_Stream {
            get {
                return ResourceManager.GetString("System.IO.Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.StringReader.
        /// </summary>
        internal static string System_IO_StringReader {
            get {
                return ResourceManager.GetString("System.IO.StringReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.IO.TextReader.
        /// </summary>
        internal static string System_IO_TextReader {
            get {
                return ResourceManager.GetString("System.IO.TextReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Linq.
        /// </summary>
        internal static string System_Linq {
            get {
                return ResourceManager.GetString("System.Linq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Math.
        /// </summary>
        internal static string System_Math {
            get {
                return ResourceManager.GetString("System.Math", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.NotSupportedException.
        /// </summary>
        internal static string System_NotSupportedException {
            get {
                return ResourceManager.GetString("System.NotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Nullable.
        /// </summary>
        internal static string System_Nullable {
            get {
                return ResourceManager.GetString("System.Nullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Object.
        /// </summary>
        internal static string System_Object {
            get {
                return ResourceManager.GetString("System.Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Private.
        /// </summary>
        internal static string System_Private {
            get {
                return ResourceManager.GetString("System.Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Reflection.
        /// </summary>
        internal static string System_Reflection {
            get {
                return ResourceManager.GetString("System.Reflection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Runtime.CompilerServices.
        /// </summary>
        internal static string System_Runtime_CompilerServices {
            get {
                return ResourceManager.GetString("System.Runtime.CompilerServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Runtime.ExceptionServices.
        /// </summary>
        internal static string System_Runtime_ExceptionServices {
            get {
                return ResourceManager.GetString("System.Runtime.ExceptionServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Security.Cryptography.
        /// </summary>
        internal static string System_Security_Cryptography {
            get {
                return ResourceManager.GetString("System.Security.Cryptography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.String.
        /// </summary>
        internal static string System_String {
            get {
                return ResourceManager.GetString("System.String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Text.
        /// </summary>
        internal static string System_Text {
            get {
                return ResourceManager.GetString("System.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Threading.CancellationToken.
        /// </summary>
        internal static string System_Threading_CancellationToken {
            get {
                return ResourceManager.GetString("System.Threading.CancellationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Threading.Tasks.
        /// </summary>
        internal static string System_Threading_Tasks {
            get {
                return ResourceManager.GetString("System.Threading.Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Threading.Thread.
        /// </summary>
        internal static string System_Threading_Thread {
            get {
                return ResourceManager.GetString("System.Threading.Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.TimeSpan.
        /// </summary>
        internal static string System_TimeSpan {
            get {
                return ResourceManager.GetString("System.TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Type.
        /// </summary>
        internal static string System_Type {
            get {
                return ResourceManager.GetString("System.Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Uri.
        /// </summary>
        internal static string System_Uri {
            get {
                return ResourceManager.GetString("System.Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.ValueTuple.
        /// </summary>
        internal static string System_ValueTuple {
            get {
                return ResourceManager.GetString("System.ValueTuple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Void.
        /// </summary>
        internal static string System_Void {
            get {
                return ResourceManager.GetString("System.Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Web.HttpUtility.
        /// </summary>
        internal static string System_Web_HttpUtility {
            get {
                return ResourceManager.GetString("System.Web.HttpUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testengine.module.
        /// </summary>
        internal static string testengine_module {
            get {
                return ResourceManager.GetString("testengine.module", resourceCulture);
            }
        }
    }
}
