locale: "en-US"
headless: false
recordVideo: true
extensionModules:
  enable: true
  parameters:
      enableDataverseFunctions: true
timeout: 1200000
browserConfigurations:
  - browser: Chromium
    channel: msedge