trigger: none
pr: none
variables:
  Codeql.Enabled: true
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    stages:
    - stage: stage
      jobs:
      - job: Build_PowerAppsTestEngine
        displayName: 'Build PowerAppsTestEngine Solution'
        strategy:
          matrix:
            Debug:
              BuildConfiguration: 'Debug'
            Release:
              BuildConfiguration: 'Release'
        templateContext:
          outputs:
          - output: pipelineArtifact
            condition: and(succeeded(), eq(variables['BuildConfiguration'], 'Release'))
            artifactName: 'PowerApps.TestEngine ($(BuildConfiguration))'
            targetPath: '$(Build.ArtifactStagingDirectory)'   
        steps:
        - script: |
            echo "Hello"
        - task: UseDotNet@2
          displayName: 'Use dotnet sdk 8.0'
          inputs:
            version: 8.0.x
            installationPath: '$(Agent.ToolsDirectory)/dotnet'
        - task: DotNetCoreCLI@2
          displayName: 'Build and test'
          inputs:
            command: 'run'
            projects: '$(Build.SourcesDirectory)/targets/targets.csproj'
            arguments: '-- ci -c $(BuildConfiguration)'
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'VSTest'
            testResultsFiles: '**/*-*.trx'
            searchFolder: '$(Build.SourcesDirectory)/obj/'
            mergeTestResults: true
            failTaskOnFailedTests: true
        - task: DotNetCoreCLI@2
          displayName: 'Pack'
          inputs:
            command: 'run'
            projects: '$(Build.SourcesDirectory)/targets/targets.csproj'
            arguments: '-- pack -c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)'
          condition: and(succeeded(), eq(variables['BuildConfiguration'], 'Release'))