name: Automate Test 

on:
  schedule:
    - cron: '10 * * * *'
    - cron: '0 6 * * 1'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
      - name: Every time
        run: echo "This step will always run"

      - uses: actions/checkout@v2
      - name: Integration Test
        env:
            user1Email: '${{ secrets.POWER_PLATFORM_USER }}'
            user1Password: '${{ secrets.POWER_PLATFORM_PASSWORD }}'
        run: |   
          cd src/PowerAppsTestEngine
          dotnet build
          pwsh bin/Debug/net6.0/playwright.ps1 install
          cd ../../build-pipelines/scripts
          chmod +x yaml-integration-tests.sh
          ./yaml-integration-tests.sh "${{ inputs.parameters }}"       # run the script with the parameter, contains logic to run the tests
      - name: Sample Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Sample Tests          # Name of the check run which will be created
          path: |
            **/*.trx
          reporter: dotnet-trx        # Format of test results      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        if: ${{always()}}
        with:
            name: 'Test Run'
            path: |
                **/TestResults/**