name: dotnet format

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - integration
  pull_request:
    branches:
      - main
      - integration

jobs:
  check-format:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@871f041373faaad213a635d9afb62905ec029bbb # v1.10.1
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Check out code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Run dotnet format
        run: dotnet format '.\src\Microsoft.PowerApps.TestEngine' --verify-no-changes --severity warn
