name: YAML Integration Tests

on:
  workflow_call:
    inputs:
      parameter:
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      - uses: actions/checkout@v2
      - name: Integration Test
        env:
            user1Email: '${{ secrets.POWER_PLATFORM_USER }}'
            user1Password: '${{ secrets.POWER_PLATFORM_PASSWORD }}'
        run: |           
          cd src/PowerAppsTestEngine
          npm install -g playwright@1.22.0
          playwright install  
          dotnet run -- -e ${{ inputs.parameter[0]}} -t ${{ inputs.parameter[1]}} -i ${{ inputs.parameter[2]}} -o ${{ inputs.parameter[3]}}; 
      - name: Sample Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Sample Tests          # Name of the check run which will be created
          path: |
            **/*.trx
          reporter: dotnet-trx        # Format of test results      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        if: ${{always()}}
        with:
            name: 'Test Run'
            path: |
                **/TestResults/**