name: YAML Integration Tests

on:
  workflow_call:

jobs:
  test:    
    name: Pass input and secrets to build_test
    runs-on: ubuntu-latest    
    steps:
      - uses: .github/workflows/build-test.yml
      - name: Integration Test
        env:
            ppuser: '${{ secrets.POWER_PLATFORM_USER }}'
            pppassword: '${{ secrets.POWER_PLATFORM_PASSWORD }}'
        run: |  
          cd ../../
          cd /home/runner/work/PowerApps-TestEngine/PowerApps-TestEngine
          cd src/PowerAppsTestEngine
          ls
          npm install -g playwright@1.18.1
          playwright install            
          dotnet run -- -e "ceb95cca-da1d-ed58-8af8-117cb4081f16" -t "f2c52b3d-d88e-4892-9785-d5b7c7016725" -i "../../samples/buttonclicker/testPlan.fx.yaml" -o "../../testResult"
          dotnet run -- -e "ceb95cca-da1d-ed58-8af8-117cb4081f16" -t "f2c52b3d-d88e-4892-9785-d5b7c7016725" -i "../../samples/nestedgallery/testPlan.fx.yaml" -o "../../testResult"